# This is a basic workflow to help you get started with Actions

name: Push Sync

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to deploy'
        # Default value if no value is explicitly provided
        default: 'master'
        # Input has to be provided for the workflow to run
        required: true

      comment:
        description: 'Target repo commit comment'
        default: 'New code changes'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Remove .env and Github actions
        run: rm .env && rm -rf .github
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          user-email: vitalii.nobis@neatbyte.solutions
          commit-message: ${{ github.event.inputs.comment }}
          destination-github-username: 'three97-dev'
          destination-repository-name: 'prehomes'
          target-branch: main
